language: c
compiler:
    - gcc
    - clang
before_install:
    - sudo add-apt-repository -y ppa:aap/kodi
    - sudo apt-get update -qq
install: sudo apt-get install -y autoconf automake xsltproc docbook-xsl libglib2.0-dev libyajl-dev libsensors4-dev libnm-util-dev libnm-glib-dev libupower-glib-dev libpulse-dev libmpdclient-dev
before_script: autoreconf -fi
script: ./configure --disable-silent-rules --enable-debug --enable-mpd-input --enable-systemd-input && make && make check
